### ISSUE TITLE
TaskRecordListByTime函数展示的任务重复了

### ISSUE THREAD

**Issue by yangzheng6678** [quanru/obsidian-periodic-para#12]
季记里的本季收集和月记里的本月收集里，展示的日记任务有重复了两遍，具体是什么导致的没有测试出来。

**Comment by yangzheng6678** [comment]
似乎是这段代码收集了日记文件

// 收集日期范围内的非日记文件
    const files = this.date.files(parsed);
    const pages = Object.values(files).flat();

    if (pages.length) {
      const nonDailyTasks = this.dataview
        .pages(`"${pages.join('" or "')}"`)
        .file.tasks.where((task: STask) => task);

      tasks = [...dailyTasks, ...nonDailyTasks];
    }

**Comment by quanru** [comment]
截个图看看？
