### ISSUE TITLE
项目readme里无法排除其他tags

### ISSUE THREAD

**Issue by mlosun** [quanru/obsidian-periodic-para#17]
比如通过插件创建了一个“搬家”的项目后，在项目readme文件里手动添加标签“日常”后，在dailynote里如果添加其他的条目“日常”后（并非希望归纳到搬家项目中的），仍然在该项目中可见。这个有没有办法解决？

**Comment by quanru** [comment]
readme 里的 tags 字段代表项目名，你如果只是想给文件加标签，直接在 readme 空白处写一个标签就可以了
