### ISSUE TITLE
窗口滚动条不生效

### ISSUE THREAD

**Issue by dark3212** [quanru/obsidian-periodic-para#18]
当Obsidian的窗口比较小时，Periodic Para 的窗口也会缩小并显示滚动条，但是滚动条无法使用。
滚动条既不响应鼠标滚轮，也不响应鼠标点击，导致最下面的添加按钮无法显示
![image](https://github.com/quanru/obsidian-periodic-para/assets/18377781/cc74cc2e-078b-41aa-a0f0-82acf6da39ca)

**Comment by dark3212** [comment]
另外是否能跟Calender一样，在点击日期或者周月年的时候自动生成或者跳转文件，不用点击+号？

**Comment by quanru** [comment]
> 另外是否能跟Calender一样，在点击日期或者周月年的时候自动生成或者跳转文件，不用点击+号？

可以的，麻烦单独新建一个 issue？
