### ISSUE TITLE
希望可以自定义 PARA模板的位置

### ISSUE THREAD

**Issue by xlglife** [quanru/obsidian-periodic-para#21]
有非常多的插件允许忽略文件夹，比如 [Linter](https://github.com/platers/obsidian-linter)，通常用于忽略模版文件夹，包括 templater 也有要求需要设定模板文件夹。

当前版本（v1.7.7）在创建 PARA 时需要 template 文件在 PARA 文件夹下，包括参考示例库采取的把周期笔记模板也放在其文件夹下，虽然能很好的治理模板较多混乱的问题，但是给使用其他插件的兼容性造成了一定困扰。

建议是能在设置页面可以自定义 PARA 模板的位置（周期笔记用在Periodic Notes可以设定）

**Comment by quanru** [comment]
具体是什么兼容性困扰呢？

**Comment by haozileung** [comment]
+1

目前遇到的一个问题，TaskListByTag，BulletListByTag会把 `0. PeriodicNotes/Templates` 里的带tag的内容也列出来。
有时会有一 些固定周期的task会通过tag关联到某个area.

期望能排除Template目录里的内容，感谢作者。

自定义模板可以提供更灵活的配置，应该是nice to have的。

**Comment by quanru** [comment]
> +1
> 
> 目前遇到的一个问题，TaskListByTag，BulletListByTag会把 `0. PeriodicNotes/Templates` 里的带tag的内容也列出来。 有时会有一 些固定周期的task会通过tag关联到某个area.
> 
> 期望能排除Template目录里的内容，感谢作者。
> 
> 自定义模板可以提供更灵活的配置，应该是nice to have的。

这个问题已经修复，请更新到 1.7.8

**Comment by quanru** [comment]
提出者仍然未回复，此处先关闭
