### ISSUE TITLE
periodic notes settings

### ISSUE THREAD

**Issue by lufan-cn** [quanru/obsidian-periodic-para#22]
periodic notes settings设定里面，API跟Token分别填写什么呢？

**Comment by quanru** [comment]
示例:
- API: https://memox.quanruzhuoxiu.repl.co/api/v1/memo
- Token: https://memos.quanruzhuoxiu.repl.co 注册一个体验

这服务只是 demo，如果有需要得自己部署

**Comment by lufan-cn** [comment]
成了！感谢大佬，另外请问一下我需要怎么样部署memo能有这个效果呢？

**Comment by quanru** [comment]
看看这里的文档：https://www.usememos.com/

replit 的话，目前可以通过这个部署，不过 2024 年要收费了：https://github.com/quanru/memos-on-replit

**Comment by lufan-cn** [comment]
好的谢谢大佬！
