### ISSUE TITLE
日记中`ProjectListByTime `未显示项目占比

### ISSUE THREAD

**Issue by zhousihan77** [quanru/obsidian-periodic-para#23]
如图：项目列表中填入耗时后，没有自动显示占比。
![example](https://github.com/quanru/obsidian-periodic-para/assets/30706939/9779cfb9-7102-479c-bbf5-13e924d3890c)

模版：

[Daily.md](https://github.com/quanru/obsidian-periodic-para/files/13820077/Daily.md)

**Comment by zhousihan77** [comment]
---更新---
1. 日记文件切换编辑和预览状态后仍不能显示项目占比。
2. 日记文件关闭重新打开后可以显示占比。
3. 模版的日记文件中，修改项目耗时后，占比公式和数值在预览状态使用新耗时，编辑状态使用旧耗时。 https://github.com/quanru/obsidian-example-LifeOS/tree/chinese-version

**Comment by quanru** [comment]
这个确实不好实现，需要定时刷新，我觉得没必要
