### ISSUE TITLE
此插件安卓手机上无效啊？

### ISSUE THREAD

**Issue by e20999** [quanru/obsidian-periodic-para#24]
我在PC上安装好后，移植到安卓手机上，[obsidian-periodic-para](https://github.com/quanru/obsidian-periodic-para)无法使用，版本号为1.7.7。请予指导为盼！想手机和PC上能同步使用。

**Comment by quanru** [comment]
无效具体是指什么

**Comment by e20999** [comment]
形如：
```PeriodicPARA
TaskDoneListByTime
```
这些语句仍是原样显示。

**Comment by e20999** [comment]
另有：Periodic PARA和Dataview插件不能开启，都是用的最新版。

**Comment by quanru** [comment]
这两个插件需要开启，你先搜搜为什么 dataview 不能开启吧，我没遇到过你说的问题

**Comment by e20999** [comment]
我将库拷至另一个华为手机上操作，一切插件和功能都对了。但我现在是在OPPO Reno4 Pro 5G手机上操作，这些相关插件就是不能启动，包括Templater插件也不能。可能的原因是什么呢？
但Tasks插件又能正常使用。
谢谢啦。

**Comment by quanru** [comment]
这个我不知道了，不是本插件的问题哈，我先关了
