### ISSUE TITLE
周记文件中，”query by time“显示错误结果

### ISSUE THREAD

**Issue by zhousihan77** [quanru/obsidian-periodic-para#25]
你好，我在使用周记功能的时候遇到query by time显示错误结果的问题，可以帮忙看下是什么原因吗？

- TaskRecordListByTime和TaskDoneListByTime在2024年W1～W9这九个文件中显示的是一样的内容。

- 其中只有W1中的结果是正确的，W2～W9文件中显示的是与file time scope不符的tasks。

- 2024-W10及以后的文件，query结果是正常的。

![week](https://github.com/quanru/obsidian-periodic-para/assets/30706939/9dd9443d-f370-486a-93c0-6fc73a88e442)

**Comment by quanru** [comment]
TaskRecordListByTime 是指本周的日记文件中记录的任务，这样还有问题吗？

**Comment by zhousihan77** [comment]
感谢你的回答，还是有一点问题：

_“本周的日记文件中记录的任务”_

这个本周是指当前时间还是周记的文件时间呢？比如现在是2024的第一周，此时新建的2024-W2周记，显示的应该是第一周还是第二周的任务呢？

在2024-01-08这天新建的2024-W2周记，显示的还是W1的任务，ProjectListByTime显示的也是上周的项目耗时。

**Comment by quanru** [comment]
所有的时间都是当前文件名的时间，和你哪一个时刻创建无关

**Comment by zhousihan77** [comment]
看起来似乎是这段代码转换week number的问题。单击日历栏生成的周记文件中，第1-9周的week number是一位数字，没办法通过W(\d{2})/)提取。

parse(path = ''): DateType {
    const fileName = this.app.vault.getAbstractFileByPath(path)?.name;

    const [[, year], [, quarter], [, month], [, week], [, day]] = [
      fileName?.match(/(^\d{4})/) || [], // year
      fileName?.match(/^\d{4}-Q(\d{1})/) || [], // quarter
      fileName?.match(/^\d{4}-(\d{2})/) || [], // month
      fileName?.match(/^\d{4}-W(\d{2})/)|| [], // week
      fileName?.match(/^\d{4}-\d{2}-(\d{2})/) || [], // day
    ];

**Comment by quanru** [comment]
@zhousihan77 已修复，请更新 1.7.9
