### ISSUE TITLE
想要的功能：usememos 唤醒

### ISSUE THREAD

**Issue by laybxc** [quanru/obsidian-periodic-para#29]
在电脑端，可以通过快捷键全局（或者局部）唤醒一个出一个框来插入memos

**Comment by quanru** [comment]
请问是 MAC 吗？是的话，建议使用这：

- https://www.raycast.com/JakeYu/memos
- https://www.raycast.com/KevinBatdorf/obsidian

插件的功能保持简单

**Comment by laybxc** [comment]
是Windows系统，个人感觉现在usememos相关支持感觉有点简单了可以稍微强化一下，比如“插入memos”、还有多一个可配置的自动同步选项？

**Comment by quanru** [comment]
目前首次打开 obsidian、每半小时都会自动同步；
抱歉，大概率不会做你说的『插入 memos』功能，社区有 obsidian memos 插件可以做这个事情了。
