### ISSUE TITLE
请教如何规划目标分解任务

### ISSUE THREAD

**Issue by e20999** [quanru/obsidian-periodic-para#32]
老师好，您这个插件很好用。我在使用中还有一些疑问请求解答：
1.如何规划目标、计划任务？
目标：年记规划目标，季记分解目标，月记拆解任务（自上而下整理：目标拆解，自下而上整理：日记/周记收集拆解）
任务：日收集周整理。
这些如何能系统连续地运用起来。
2.计划复盘具体做什么，怎么做？
复盘：周记复盘本周日记，月记复盘每周复盘，季记复盘每月复盘。年度复盘每季记录，周记、月记复盘项目，要事维度是项目；季记、年度复盘领域，要素维度是领域。
在计划复盘时，具体该怎么做？
谢谢老师予以解答。

**Comment by quanru** [comment]
咨询问题去微信搜『被减数』入群吧，这里不解答这类问题哈
