### ISSUE TITLE
[Incompability] 新版 usememos 无法同步图片等附件 

### ISSUE THREAD

**Issue by panwanke** [quanru/obsidian-periodic-para#35]
今天突然发现，usememos 的 docker 最新版本已经升级到 0.19.0了，但是 github 还是 0.18.2。

在新版本中，需要使用 resource.name 而不是 resource.id 才能正确获取附件的二进制内容。不然下载的附件是空的。

https://github.com/quanru/obsidian-periodic-para/blob/main/src/periodic/DailyRecord.ts#L123
```js
const { data } = await this.axios.get(
              `${origin}/o/r/${resource.name}`,
              {
                responseType: 'arraybuffer',
              }
            );
```

**Comment by quanru** [comment]
老版本用 name 可以吗？

**Comment by quanru** [comment]
fixed in version 1.8.5
