### ISSUE TITLE
创建PARANotes时的tag能够做一下提示吗？

### ISSUE THREAD

**Issue by AILHC** [quanru/obsidian-periodic-para#36]
现在是没有提示的，得手敲，哈哈
虽然没多大问题，因为这个需求很弱

**Comment by quanru** [comment]
是指自动补全吗？

**Comment by AILHC** [comment]
> 是指自动补全吗？

就是库里有哪些标签，有个下拉列表提示一下

**Comment by quanru** [comment]
> > 是指自动补全吗？
> 
> 就是库里有哪些标签，有个下拉列表提示一下

是个好建议，一直想做，我自己也每次去复制之前的，我记着了
