### ISSUE TITLE
[feature] bullet的file跳转和预览

### ISSUE THREAD

**Issue by AILHC** [quanru/obsidian-periodic-para#38]
由于可能在bullet记录相对长的一段，但dataview的table没法显示全，而且file跳转又只跳转到文件
虽然问题不大，但内容比较多的日志会很烦

能否支持跳转到某个标题下，或者有blockid的列表项？

我简单修改了一下bullet的查询显示逻辑，暂时实现了这个功能
```js
let querySQL = `
      TABLE WITHOUT ID rows.L.text AS "Bullet",rows.L.link AS "Link"
      FROM (${from2}) AND -"${periodicNotesPath}/Templates"
      FLATTEN file.lists AS L
      WHERE ${where} AND !L.task AND file.path != "${filepath}"
      GROUP BY file.link
      SORT rows.file.link DESC
          `;
```
![image](https://github.com/quanru/obsidian-periodic-para/assets/21373809/c50c928f-c648-4793-8572-cbe0ae4a44b5)

**Comment by quanru** [comment]
如果没有 blockid 会怎么跳转？

**Comment by AILHC** [comment]
> 挺棒的，如果没有 block id，得想个方式默认都加上

是的，我不知道行不行，因为我想dataviewjs那个是被动查询，改到文件不太好。
哈哈，但其实定位到标题就已经够了。

**Comment by quanru** [comment]
> > 挺棒的，如果没有 block id，得想个方式默认都加上
> 
> 是的，我不知道行不行，因为我想dataviewjs那个是被动查询，改到文件不太好。 哈哈，但其实定位到标题就已经够了。

我已经采用了你的方式了，下次发版带上~
