### ISSUE TITLE
关于daily-note tag出问题

### ISSUE THREAD

**Issue by lufan-cn** [quanru/obsidian-periodic-para#40]
升级到periodic PARA 1.9.0之后，同步memos笔记的时候tag经常会分开，如下图，随机出现并没有发现什么规律，另外版本分别为memos: v0.19.1; obsidian: v1.5.3。
![微信图片_20240206113306](https://github.com/quanru/obsidian-periodic-para/assets/108657957/2775be5d-3897-4a59-bd20-07b4a44aae2e)

**Comment by lufan-cn** [comment]
最近几天不会这样了。

**Comment by quanru** [comment]
@lufan-cn 感觉不是插件的问题，插件只做了文本拼接

**Comment by lainding** [comment]
是否可以把这个 **#daily-record** 的tag做成配置参数，个人根据需要自定义，这样就不会影响自己的tag系统了。
