### ISSUE TITLE
usememos同步的逻辑有些黑盒，而且memos内容不会更新

### ISSUE THREAD

**Issue by AILHC** [quanru/obsidian-periodic-para#41]
看了一下代码，应该是每次启动时同步memos吧？
或者开关配置时同步，没看到其他同步的按钮或者命令

我的memos内容已经更新了，但同步的时候会跳过，看起来是根据创建时间来判断是否需要同步

而且只同步当天的是吗？

**Comment by quanru** [comment]
有两个同步命令，策略是不会覆盖同步，如果需要覆盖，请用 force 同步命令
