### ISSUE TITLE
ResourceListByTag error

### ISSUE THREAD

**Issue by nicky-johnson** [quanru/obsidian-periodic-para#42]
ResourceListByTag produces the same results as ResourceListByFolder; a list of folders instead of a list of tags used by files.

eg
folder 1
 - file1.README
    - tag: test

expected result would be
- test

Actual result:
- folder 1

**Comment by quanru** [comment]
It is indeed designed like this to list the Resource list in Home.canvas.

![image](https://github.com/quanru/obsidian-periodic-para/assets/11739753/0ab3c958-4a63-4206-9113-1e1fe3602855)

**Comment by nicky-johnson** [comment]
Is it designed the show the tag names or the folders?

**Comment by quanru** [comment]
Show the folders，the tag is just a id for folder~
