### ISSUE TITLE
使用Boarder主题时，插件背景变化导致无法看清

### ISSUE THREAD

**Issue by lainding** [quanru/obsidian-periodic-para#43]
如图，分别是日历和PARA的情况。

![image](https://github.com/quanru/obsidian-periodic-para/assets/5516006/78088065-9afe-4ce1-ab40-ffa7ddfaf933)

![image](https://github.com/quanru/obsidian-periodic-para/assets/5516006/554922bb-9c5b-45fc-90be-168987927d1a)

**Comment by quanru** [comment]
重新打开一次 Obsidian 呢？

**Comment by lainding** [comment]
情况一样。

**Comment by quanru** [comment]
你是不是用了 style settings？

**Comment by lainding** [comment]
是的。

**Comment by quanru** [comment]
关了 style settings 是否正常？如果是，然我看看你配置了什么

**Comment by lainding** [comment]
关了style settings是正常的。下面是style setting的配置。
{
  "minimal-style@@h2-size": "1.2em",
  "minimal-style@@h3-size": "1.2em",
  "minimal-style@@h4-size": "1em",
  "minimal-style@@h5-size": "1em",
  "minimal-style@@h6-size": "1em",
  "minimal-style@@code-size": "12px",
  "minimal-style@@blockquote-border-color@@light": "#0C73A6",
  "minimal-style@@blockquote-border-thickness": 3,
  "minimal-style@@ribbon-style": "ribbon-hidden",
  "minimal-style@@checkbox-shape": "checkbox-square",
  "minimal-style@@tag-radius": "14px",
  "minimal-style@@minimal-unstyled-tags": false,
  "minimal-style@@tag-border-width": "1px",
  "Editor@@h2-divider-on": false,
  "Editor@@h3-divider-on": false,
  "Components@@CTA-BTN-enable": true,
  "Components@@file-names-untrim": false,
  "Components@@folder-font-bold": true,
  "Components@@vault-name-display-select": "vault-name-default",
  "Components@@colorful-folder": false,
  "Components@@file-icon-remove": false,
  "Components@@new-tab-btn-select": "new-tab-btn-default",
  "Components@@new-tab-image-select": "new-tab-image-default",
  "Components@@tab-autohide": true,
  "Editor@@codeblock-style-select": "codeblock-style-solarized-light",
  "Editor@@inline-code-background-light": "\"\"",
  "Editor@@inline-code-normal@@light": "#606060",
  "Appearance-light@@card-layout-open-light": true,
  "Appearance-light@@card-border-radius-light": "8px",
  "Appearance-light@@theme-light-style-select": "theme-light-background-default",
  "Editor@@blockquote-background-light": "\"\"",
  "Editor@@callout-style-select": "callout-style-4",
  "Editor@@table-header-background-light": "\"\"",
  "Appearance-light@@card-highlight-light": false,
  "Editor@@bold-color@@light": "#5F5F5F",
  "Appearance-light@@accent-light": "#0A77AC",
  "Appearance-light@@accent-color-override-light": true,
  "Plugin@@Projects-bg-color": "Projects-bg-color-default",
  "Plugin@@colorful-checkbox": false,
  "Plugin@@DB-table-full-width-off": false
}

**Comment by quanru** [comment]
我找到问题了，你 Command+p 重新载入一下窗口

![image](https://github.com/quanru/obsidian-periodic-para/assets/11739753/7c97c2ee-af1a-4119-ab80-b11d66482f17)

怎么解决我还得想想

**Comment by quanru** [comment]
close by version 1.9.4
