### ISSUE TITLE
插件界面缩放问题

### ISSUE THREAD

**Issue by Thinkbond** [quanru/obsidian-periodic-para#45]
![image](https://github.com/quanru/obsidian-periodic-para/assets/9856020/ca1733fb-6238-488e-84fc-f4ce369115b3)
请问是否可以调整一下界面缩放，目前如果想把侧边栏空间缩小一些，日历及日记、周记等按钮会显示不完整，且没有类似滚动条的方式打开，必须依赖拖动界面大小来实现。谢谢！
看项目主页介绍中的截图缩放效果不错，不过我使用 Windows 10（1920×1080）、Windows 11（1366×768的ThinkPad） 、macOS Ventura（4K，21寸iMac）均复现了上述问题，实测日历区和日记周记等按钮的界面占比过大。

**Comment by quanru** [comment]
你这两个分别设为多少？我是 16 和 83%
![image](https://github.com/quanru/obsidian-periodic-para/assets/11739753/e9070e25-d648-4a43-b8c2-2fa088571f9e)

**Comment by Thinkbond** [comment]
> 你这两个分别设为多少？我是 16 和 83%

我的缩放是默认值，个人理解一般情况下用户不会刻意调整缩放比例。建议做一些调整，感谢🙏
附全屏截图，这是我能调到的能显示完整的最小面积了，相对来说，插件面积过大，主要编辑区域相对捉襟见肘，供参考。
![image](https://github.com/quanru/obsidian-periodic-para/assets/9856020/d5cebd5c-97ff-4d2d-b314-f04efe655d2b)

**Comment by quanru** [comment]
如果不调整缩放和字体，无论怎么调整，对你来说都是太大的

**Comment by Thinkbond** [comment]
> 如果不调整缩放和字体，无论怎么调整，对你来说都是太大的

如果我按照16号字和83%缩放会得到这样的效果，😅
![image](https://github.com/quanru/obsidian-periodic-para/assets/9856020/566522be-efdd-499f-b699-7545be7ae995)
字体非常小，看不清。

**Comment by Thinkbond** [comment]
Obsidian 中的 Calendar 插件的大小相对来说占用面积不大。

**Comment by quanru** [comment]
缩放 83%，继续调大字体大小就好了啊

**Comment by quanru** [comment]
calendar 插件如果也在左侧上下排列，也是占位置的吧，你截图对比下？你在意这个的话，就只能左侧放置一列，而不是分栏了

**Comment by quanru** [comment]
我想想咋搞，我的插件确实比 calendar 多了功能，所有多了两栏

**Comment by Thinkbond** [comment]
辛苦了，感觉可以先把日历中字符间距、字体大小调整一下。

**Comment by quanru** [comment]
![image](https://github.com/quanru/obsidian-periodic-para/assets/11739753/a27b5657-2b8f-4a16-b00f-c923d572ada8)

@Thinkbond 更新插件到 1.11.0 试试

**Comment by Thinkbond** [comment]
👍
