### ISSUE TITLE
[FeatureRequest] BulletListByXXX 生成的 Dataview List 改为每一行一条数据

### ISSUE THREAD

**Issue by wty21cn** [quanru/obsidian-periodic-para#48]
BulletListByXXX 生成的 Dataview List 当前一行可能包含多个 List 数据，比如领域和项目中用到的 BulletListByTag 可能因为一天的 daily note 中多次出现同一个 tag，从而展示成一行里面第一列多个 bullet，第二列为这个文件的多个 link。

当每个 bullet 较短时，两列的对齐没有问题，但是当第一列内容较长且开启了 table text wrap 导致文本换行时，第二列 link 文字比较少没有换行，就会出现第一列和第二列的没有对齐问题，不方便跳转的问题

**Comment by quanru** [comment]
因为 GROUP BY file.link 了，所以同一个文件都在一行表格里了，你找找有什么语法，我没找到解法
