### ISSUE TITLE
resource with image as externalLink generates invalid markdown

### ISSUE THREAD

**Issue by jeffutter** [quanru/obsidian-periodic-para#57]
I have a memo setup that hosts files (including images) in S3 compatible storage.

The resource returned from the memo API has a direct link to the image under `externalLink`.

Given that, this code here: https://github.com/quanru/obsidian-periodic-para/blob/22046390e73b9e6a517a43eff15fa5847c513192/src/util.ts#L122-L129 generates invalid markdown. 

It generates `![[http://mydomain.com/files/path/to/file.png]]`. 

That syntax is expecting a local file. Ideally, this plugin would download the linked file and store it in my vault. However, second to that generating a valid markdown image embed like `![file.png](http://mydomain.com/files/path/to/file.png)` would also be OK. 

The resource payload includes `type: "image/png"` so we could hopefully use that to detect images that should generate different markdown.

**Comment by quanru** [comment]
1. external link can't be download due to cors problem
2. how to deal with external link which is not image?

**Comment by quanru** [comment]
close by version 1.12.3
